### ISSUE TITLE
Dropped samples

### ISSUE THREAD

**Issue by bigalnz** [artursartamonovs/pyairspyhf#1]
Hello,

Sorry for the weird way to reach out to you. I have also written a wrapper but have issue with dropped samples on the ctypes call back. Do you have this issue too?

Al

**Comment by artursartamonovs** [comment]
What function you see and it have this issue. Its plain C to Python translation, then C should also have this issue. And no I haven't seen any missing samples reported from libairspyhf

**Comment by bigalnz** [comment]
Hi Arthur

Are you ok for email? I would very much like to talk.

Al

**Comment by bigalnz** [comment]
I changed test.py to this:

`def read_samples(transfer):
    global sample_count
    global wave_file
    #print("Python call back")
    t = transfer.contents
    if t.dropped_samples > 0:
        print('Dropped samples',  t.dropped_samples)
    bytes_to_write = t.sample_count * 4 * 2
    rx_buffer = t.samples
    #print(f"{bytes_to_write} bytes receieved")
    sample_count += t.sample_count`

Then I run it:

Cant load dll airspyhf.dll 0
Set libairspyhf version 1.7.1 (Actual version (1.8.0)
Check airspyHF version
None
1
8
0
Get list of devices if there is any
Found 1 devices
Device 0: Serial number 0xdc52978027444a4d
try to open device
open_sn: Returned 0
List sample rates
ret 0
sample rates 7
ret 0
Sample rates 912000
Sample rates 768000
Sample rates 650000
Sample rates 456000
Sample rates 384000
Sample rates 228000
Sample rates 192000
airspyhf_set_samplerate ret=0
airspyhf_set_hf_agc ret=0
airspyhf_set_hf_agc_threshold ret=0
airspyhf_start ret=0
airspyhf_set_freq ret=0
Main loop
Main loop
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 6144
Dropped samples 6144
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Main loop
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 6144
Dropped samples 6144
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096
Dropped samples 4096
Dropped samples 4096
Dropped samples 6144
Dropped samples 4096

My AirSpyHF is running latest FW which I think is R4.0.8 2024-03-14

**Comment by artursartamonovs** [comment]
I dont think this is testing anything meaningful. Better test would show how many samples are in total read. Find ratio dropped vc received. And of course per each second. I may check that latter. At  this stage can't see anything to tell there is actual issue. And size looks 4K suggests that its default buffer/transfer size, maybe buffer isn't full and its get dropped as there is no meaning to transfer non-full buffer. More checks/tests needed, and also I don't think then is python issue or python binding issue.
